name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Paper.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Paper.pdf
      - name: Configure Git
        run: |
          git config user.name "Aidans Tex Bot"
          git config user.email "aidan@google.com"
      - name: Add and commit PDF to repository
        run: |
          git add Paper.pdf
          git commit -m "Add compiled PDF"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
